### ISSUE TITLE
continuation of previous issue

### ISSUE THREAD

**Issue by kairajohnson** [ga-wdi-exercises/project4#181]
I didn't get to your last suggestion until now. I have updated my repository and am having the same issue. for my length, it has 0. I tried reseeding my data, console logging, and going back on our material but don't really understand what I'm doing at this point to pinpoint the issue.

https://github.com/kairajohnson/gentrification.git

**Comment by RobertAKARobin** [comment]
The problem is in this section:

https://github.com/kairajohnson/gentrification/blob/master/index.js#L33

This defines the `/api/contributors` GET route, from which Angular tries to get all the contributors information.

This route is currently not working. You can test it by going to `localhost:3000/api/contributors` in your browser: it just hangs forever until eventually you get a "timeout" request.

That's because line 36 is telling Express to do something with `req.session`. `req.session` doesn't exist. It exists only if you've set up `express-session` and all its dependencies, and you haven't done that yet. This is good -- I wouldn't do it until much further down the road.

Simply comment out line 36 and see what happens.
