### ISSUE TITLE
Problems with Synchronicity

### ISSUE THREAD

**Issue by Ceisen9** [ga-wdi-exercises/project4#196]
Hi Robin and Adrian,

I am struggling with getting my CRUD functionality to work in real time. In my app, on the index page, I can add as many favorite shows as I want to a user object and they will show up as expected, but when I go back to refresh only the first one I submitted will be saved. Similarly, on the show page, I can add as many episodes to a show that I want to a show object, but again when I refresh only the first one added is still there. The same is true for deleting multiple episodes on the show page; only the first one I delete will persist in the database despite showing up like it should in the browser.  Would one of you mind taking a look at my code please? 

https://github.com/Ceisen9/show-stopper/tree/migrate-schema

I think I'm querying the database wrong in my User factory but I can't figure out how to fix it. This code is in the public >  js > app.js file.

**Comment by amaseda** [comment]
Cloning this down and taking a look.

**Comment by RobertAKARobin** [comment]
I don't know if this is the problem, but this looks really odd to me:

``` js
  function User($resource){
    var vm = this
    var User = $resource("/api/shows", {}, {
      update: {method: "PUT"},
      'query': {method: 'GET', isArray: false }

    });

    var user = User.query();
    return user
  }
```

Here's what's weird:
- `var vm = this` -- This is just a semantic point, but a viewmodel (`vm`) is an instance of a controller. This User is a resource, which is a different thing. A viewmodel is an interface between the view and the controller; a resource is an interface between the controller and the database.
- `var user = User.query(); return user` -- You probably want to be returning `User`, rather than `user`. I'd recommend `User.all = User.query()`, like, we've done in class.

If the second one's a deliberate choice I'm all ears, but it makes this difficult to read.
