### ISSUE TITLE
Adding Task to List

### ISSUE THREAD

**Issue by winishahines** [ga-wdi-exercises/project4#199]
I'm trying to add the ability to create a task on a task list via a form but I get the following error:

![snip20160428_2](https://cloud.githubusercontent.com/assets/16657107/14887973/098e299c-0d26-11e6-8732-ac6bd12fee47.png)

Ideally I want to do something like "simple form_for [@task_list, @task_list.tasks.build]" but it looks like I needed to pass in @user first and ruby can't find the tasks path. I also tried doing  @task_list.new_user_task_list_task.build, where "new_user_task_list_task" is the route associated with creating a new task but that didn't work either. Any thoughts?

**Comment by winishahines** [comment]
Since the issue is occuring in my show method for the tasklist controller I tried updating it to include tasks but it still didn't work. Here's the code and my new error:

![snip20160428_3](https://cloud.githubusercontent.com/assets/16657107/14892112/68226c6e-0d37-11e6-8d72-0bb91720fb23.png)
![snip20160428_4](https://cloud.githubusercontent.com/assets/16657107/14892119/6bc5f7d2-0d37-11e6-9913-04b2dca19b5b.png)

**Comment by RobertAKARobin** [comment]
This looks like progress. This second error is happening because of problems with the form. Can you paste your form's code?

**Comment by winishahines** [comment]
![snip20160428_6](https://cloud.githubusercontent.com/assets/16657107/14892417/b16e07e2-0d38-11e6-8a63-2974b29861f4.png)

**Comment by RobertAKARobin** [comment]
Could you push your code up and link to your repo?

**Comment by winishahines** [comment]
The changes are on the add_tasks_to_lists branch. Here's the link:

[UnDone](https://github.com/WinishaSmith/UnDone/tree/add_tasks_to_lists)

**Comment by RobertAKARobin** [comment]
I'm confused at to what this `show` route should be doing. It doesn't do anything, it just redirects to another page. Is that what you intended?

**Comment by winishahines** [comment]
I want the task form to appear on the tasklist show page so that whenever I enter a new task it appears on the list. Is there a better way of doing this?

**Comment by RobertAKARobin** [comment]
Well, `redirect` is always going to take the user to a completely different URL -- they're never going to see that `show` page. So delete that `redirect` line altogether unless there's a really good reason to have it.

Then, you'll get that `param is missing` error. That's because you're doing `.build(task_params)`. That `task_params` is really only meant to be used when someone **submits** a form -- not when you're just trying to **view** a form.

When you fix that, you'll get that `undefined method 'tasks_path'` error again. There are two reasons for that:

1) `@user` is undefined. You haven't defined it in your controller.

2) `[@user, @task_list.tasks.build]` would work if `tasks` were nested under `users`, but they're not: they're nested under `task_lists`, which are nested under `users`. So you need to put `task_list` in there too:

``` erb
<%= simple_form_for [@user, @task_list, @task_list.tasks.build] do |f| %>
```

There are 3 things in that array, one for each level of nesting.

**Comment by winishahines** [comment]
Great thanks! I was sure if I could pass in three parameters since most of the examples online only had two. I can see the form on the task list now but I'm encountering a new error when I submit. I'm going to review a little further but I'd like to keep this open just in case I can't figure it out.

**Comment by RobertAKARobin** [comment]
👍

**Comment by winishahines** [comment]
I fixed it!!!! Closing.
