### ISSUE TITLE
rails with reactJS 

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/project4#234]
I'm brainstorming project ideas and have some general questions.. 
I'm thinking of using rails with front-end Reactjs - is this considered a strange paring? and do you think its possible to implement in our timeframe?  I saw that there is a gem to incorporate react with rails but might be easier to deploying them separately. also, on the last project, it was discouraged to use user / user authentication with angular b/c it was considered difficult to implement within the time frame we were working with (well, that was one reason). It is also considered relatively difficult to implement user auth with reactJS?

**Comment by nolds9** [comment]
No, definitely not strange. There's an awesome gem to help with that stack
https://github.com/shakacode/react_on_rails

User Auth is not impossible, just a little complex. The issue is the same with react, angular, or any CLIENT side tool - authentication will require some way to keep the server - client in sync, usually done via JSON Web Tokens.
There's some more info on doing that with react and rails here https://labs.chie.do/authenticating-your-reactjs-app-with-devise-no-extra-gems-needed/?utm_source=Rails%20Forum&utm_medium=Answering%20Posting&utm_campaign=Rails-forum-answer--posting

**Comment by JuliaNajafi** [comment]
thank you!! those links are very helpful !
