### ISSUE TITLE
Associations in Rails and displaying Project info on User Show Page

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project4#235]
I was talking to Nick and Adrian earlier about this, is this what you two were talking about? If yes, my question is then, how do I add a User to a Project? Can I? Or do I need to create another Project Model (TeamProject?) that can take an array of Users?

projects_controller.rb

```
  def create
    @project = Project.find_or_create_by(project_params)
    UserJoinProject.create!({user: current_user, project: @project})
    redirect_to current_user
  end
```

UsersJoinProjectsController (was getting confused using "Teams")

```
def create
    @project = Project.find(params[:project_id])

    # can't really move to model
    if @project.user_join_projects.first
      flash[:danger] = "There is already a Team for this Project"
      redirect_to @project
    else
      @user_join_project = UserJoinProject.create!(user_join_project_params.merge({user: current_user}))
      redirect_to @project
    end
  end
```

Users Helper, use the below function in the User Show View

```
module UsersHelper
  def select_user_proj
    @user.user_join_projects.select{ |proj| proj.user_id == current_user.id }
  end
end
```

**Comment by nolds9** [comment]
@dcordz this looks similar to what I was thinking about...have you tested it? I'd try it in the console, if it doesn't work let us know what the errors are

**Comment by dcordz** [comment]
Yep it works fine for displaying data on a User show page, but I'm more curious about what will happen when another User makes the same project.

I'm leaning towards making a new Project (versus merging a User into a Project) which has both Users on it, but would I then have to update my schema so that a Project can have an array of users rather just user_id?

**Comment by amaseda** [comment]
Have you tested to see what happens when a user creates the same project based on the code you have now? 

If possible, I would recommend taking advantage of the ActiveRecord methods available to you by using a many-to-many relationship (like `@user.projects` and `@project.users`). You could replicate those by storing an array in a table, but you'll have to do some extra work.

If you go with the new approach you mentioned, then yes, you would need to update your schema.
