### ISSUE TITLE
Question about Postman

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/project4#328]
I'm trying to test POST crud on a model using Postman:

```
// schema
var UserSchema = new Schema({
  email: String,
  name: {
    first: String,
    last: String
  }
})

// route / controller
app.post('/api/users', function(req, res) {
  User.create(req.body, (err, user) => {
    if (err) console.log(err)
    else console.log(user)
  })
})
```

I am able to create a new record using Postman but not able to send in the nested `name` field. Here's what I was trying:
![image](https://cloud.githubusercontent.com/assets/3825779/20406969/784e6ebc-acdd-11e6-8acb-1f7a9d890c85.png)

I tried both `{first: "bar", last: "bar"}` and `{"first": "bar", "last": "bar"}`. Any idea how I can test this successfully?

**Comment by amaseda** [comment]
What happens if you define `Content-Type` to be `application/json` under the Headers section?

Another thing to try: select the "raw" radio button and type out your request entirely in JSON. If you end up trying this out, there should be a new option to select what data type you are sending to the right of the "binary" radio button.

**Comment by bcope** [comment]
Raw worked. Thanks!!!

**Comment by amaseda** [comment]
:+1:
