### ISSUE TITLE
General Questions about MEAN

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project4#456]
Hey Adrian, 

Per my request, I was hoping we could find a few minutes to chat about general questions I have on the MEAN stack, specifically: 

What dependencies need to be added for apps? 
	-does handle bars need to be installed for Angular?	(I'm assuming no, but I dont think I understand the relationship enough to cut it out) 
	-if I did -g nodemon on a prior project do I ever need to install again? Why doesn’t it come up on the dependencies if not?

What is the best way to build an app? Back to front? Bounce back and forward between views and controllers? As I mentioned, right now I just dont have a good process and any suggestions would be really helpful.

What needs to be running in the background to view local host? 

Here is the repo as well that I'd like to talk you through so you can see how I'm approaching it currently: https://github.com/nrc0004/project4

Thanks again!

**Comment by amaseda** [comment]
#### dependencies

If you're going to build a mean app, you'll at least need the following...

- `express`
- `mongoose`
- `body-parser`

#### handlebars

Nope, if you're using Angular then that's what's going to handle rendering data on the page dynamically (i.e., you'll be using Angular's version of `{ data goes in here }`. You would only use handlebars if using server-side rendering throughout your app.

#### nodemon

`nodemon` does not need to be listed as a dependency on your app. It's just something you use on a server (in your case locally) to run the file that contains your Express app.

#### localhost

If you're building a MEAN app, you should only need to run `nodemon` in order to view your app at `localhost`.

Why? Because `nodemon` will trigger the `index.js` file that contains your Express app. You're Express app will in turn serve up an `index.html` file that will contain `<script>` reference to Angular, which will then load your front-end app.

Because you're rolling everything into one, there's no need to run `nodemon` and `hs` at the same time.

**Comment by amaseda** [comment]
#### building the app

I would start with the back-end. Build out your API, serve up some JSON, and make sure that you can view that root `index.html` file in the browser.

From there, start building out your Angular app.

**Comment by amaseda** [comment]
Was the above helpful? Let me know if I can elaborate / answer any other questions.

@nrc0004

**Comment by amaseda** [comment]
Going to close this for now but feel free to re-open if you have additional questions/comments.
