### ISSUE TITLE
trouble with getting params into url api

### ISSUE THREAD

**Issue by edawson1980** [ga-wdi-exercises/project4#494]
Hey,

I'm using react to build a two-part app.  The first part lets a user get information about every branch in the DC public library system.  The second part is a search form that lets a user search by title, author, or ISBN to find a book online.  My problem right now is with the second part.
I'm using the GoogleBooks API, and it works in Postman.  However, I'm not able to get the information entered into the search fields to jump into the url I'm using for my GET request.  I'm using the react-translate as a guide, but clearly I'm missing something.

https://github.com/edawson1980/library-finder/tree/maps

Thanks.

**Comment by jsm13** [comment]
This is the request being made [here](https://github.com/edawson1980/library-finder/blob/maps/src/components/SearchContainers/SCWhat.js#L23-L36)? Do you get an error or any response?

**Comment by edawson1980** [comment]
That's what I'm shooting for yes.  I don't get any error, or response, but
it does work in Postman (when I manually fill in the values for intitle and
inauthor.

**Comment by jsm13** [comment]
Oh, I think it's just that you need to add an `onSubmit` callback for the form. So [this line](https://github.com/edawson1980/library-finder/blob/maps/src/components/SearchContainers/SCWhat.js#L41) would be `<form onSubmit={this.handleSubmitSearch}>`. You'll also want to bind the `handleSubmitSearch` to `this` in the constructor so that `this.state` context remains SCWhat. See [controlled components](https://facebook.github.io/react/docs/forms.html#controlled-components) in the react docs

**Comment by edawson1980** [comment]
Oh, fantastic.  Thank you!  I'm getting an XML object as a response now,
but the important thing is that I'm getting a response.
