### ISSUE TITLE
Question about Encrypting API Keys with PHP / MySQL

### ISSUE THREAD

**Issue by mpopv** [ga-wdi-exercises/project4#71]
I'm building a theme-that's-really-more-of-an-app for Wordpress.

I've already implemented a couple backend options panels that allow a user to perform CRU actions on an object called theme_mod that encapsulates values for (potentially) lots of different option keys. Using theme_mod allows users to adjust the options via the WP backend's Customizer screen. Keeping option panels within the Customizer screen 1) ensures forward compatibility with WP.com's Calypso platform, and 2) is the only way to prevent automatic rejection from WP.org's theme directory. For these reasons, I'd like to stick to storing these values via theme_mod if possible.

I'd like the user to be able to store API keys for Facebook and Twitter via these option panels as well, in order to generate social feeds.

I'm wondering if it's necessary /  advantageous to encrypt the keys before they are saved into theme_mods.

I'm leaning toward 'no' because this is a backend-to-backend operation, and (from what I understand about PHP and WordPress) only the compiled HTML/CSS/JS is served to the user. [Also StackOverflow seems to think it's not necessary](http://security.stackexchange.com/questions/18572/is-it-okay-for-api-secret-to-be-stored-in-plain-text-or-decrypt-able). But isn't it bad practice to store passwords as cleartext? Maybe that doesn't apply in this instance because it's a CMS add-on, so the user is the one maintaining the database?

**Comment by RobertAKARobin** [comment]
Good question! Even if you encrypt your keys, you'll need to save the key to your encryption as plain text somewhere -- so if anyone has access to your server, they'll be able to figure it out pretty quickly anyway. If this was something client-facing then you'd absolutely need to encrypt it, but since it's only server-facing it's not necessary. If someone's in a position where they're trying to decrypt server-facing stuff then you have much bigger fish to fry. :)

**Comment by mpopv** [comment]
Okay cool, that's what I thought. Thanks Robin!

(Feel free to close)
