### ISSUE TITLE
Displaying data from second API in angular

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#96]
I'm trying to add comments to my existing posts show view in Angular.  Have set up the API endpoints for comments, but wonder whether I should build a parallel structure for comments - CommentFactory, show, new, etc. - or incorporate comments into existing post file structure.

I've started with the former - created new directory /comments and added factory, show.html, show.controller, comments.js files - and modified posts/show.html to pull data from comments api.  I expected comments to show here, but do not see any data or error messages.
1. am i building a new module, comments?
2. code i'm using to display comments in posts/show.html is

```

<!-- run through comments here to show? -->
<div data-ng-repeat="comment in CommentIndexViewModel.comments">
  <blockquote><a data-ui-sref="commentShow({post_id: post.id, id: comment.id})">{{comment.commentBody}}</a></blockquote>
</div>
```

My api repo is https://github.com/thomhouseholder/runners-app, and my front end repo is https://github.com/thomhouseholder/runners-angular

**Comment by RobertAKARobin** [comment]
Really good question! Truth be told, I don't think there's a right answer. I'd like to say build a whole new model because I like building models. But unless there's stuff you're going to specifically be doing with comments that you won't be doing with posts then it's not really necessary.

I'd say the test is: do you need to create a Comment Factory or Service? If so, it should be its own module. If not, then there's no need.

I ran into the same thing when playing around with Grumblr. You can see at the link below that I have a Comment module... but it has no dependencies. I have a Comment Factory... but it does literally nothing. And Comments can't exist without Posts anyway, so they may as well just be attached to the same module.

https://github.com/RobertAKARobin/angular_message_board/tree/master/js/comment

**Comment by ghost** [comment]
okay, helpful stuff.  is your comments code above incorporated into grumblr on github?  seeing it in context will help me.

**Comment by RobertAKARobin** [comment]
Nah, it's independent of Grumblr, but they're similar. If you want to see a working version, you can go to http://robertakarobin.github.io/angular_message_board/ .

**Comment by ghost** [comment]
k, cool.
